"""empty message

Revision ID: 03aa688c99c7
Revises: 154822c22c24
Create Date: 2022-11-14 15:16:30.595937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03aa688c99c7'
down_revision = '154822c22c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashCode', sa.String(length=120), nullable=True))
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    op.create_unique_constraint(None, 'user', ['hashCode'])
    op.create_unique_constraint(None, 'user', ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.drop_column('user', 'hashCode')
    # ### end Alembic commands ###
