"""empty message

Revision ID: 154822c22c24
Revises: b03adda1d5c0
Create Date: 2022-11-14 15:08:15.622611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '154822c22c24'
down_revision = 'b03adda1d5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user')
    op.add_column('group', sa.Column('groupCode', sa.String(length=4), nullable=True))
    op.drop_index('hashCode', table_name='group')
    op.create_unique_constraint(None, 'group', ['groupCode'])
    op.drop_column('group', 'hashCode')
    op.add_column('user', sa.Column('hashCode', sa.String(length=120), nullable=True))
    op.drop_index('ix_user_firstname', table_name='user')
    op.drop_index('ix_user_lastname', table_name='user')
    op.create_unique_constraint(None, 'user', ['hashCode'])
    op.create_unique_constraint(None, 'user', ['password_hash'])
    op.drop_column('user', 'hashcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashcode', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_lastname', 'user', ['lastname'], unique=False)
    op.create_index('ix_user_firstname', 'user', ['firstname'], unique=False)
    op.drop_column('user', 'hashCode')
    op.add_column('group', sa.Column('hashCode', mysql.VARCHAR(length=4), nullable=True))
    op.drop_constraint(None, 'group', type_='unique')
    op.create_index('hashCode', 'group', ['hashCode'], unique=False)
    op.drop_column('group', 'groupCode')
    op.create_table('group_user',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='group_user_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
