"""empty message

Revision ID: 38cc95797964
Revises: 03aa688c99c7
Create Date: 2022-11-14 16:33:26.598047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cc95797964'
down_revision = '03aa688c99c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group_User',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('group', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'user', ['admin_id'], ['id'])
    op.add_column('poll', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('poll', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poll', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'poll', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_column('poll', 'group_id')
    op.drop_column('poll', 'creator_id')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'admin_id')
    op.drop_table('Group_User')
    # ### end Alembic commands ###
