"""empty message

Revision ID: 512d604ecd8e
Revises: 044817cf9c95
Create Date: 2022-12-12 13:54:50.566964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '512d604ecd8e'
down_revision = '044817cf9c95'
branch_labels = None
depends_on = None


def upgrade():
    
    op.add_column('group', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('year', sa.Integer(), nullable=True))
    op.alter_column('group', 'groupimage',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'groupimage',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('group', 'year')
    op.drop_column('group', 'month')
    op.drop_column('group', 'day')
    op.create_table('group_user',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='group_user_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_poll_option_optionname'), table_name='poll_option')
    op.drop_index(op.f('ix_poll_option_description'), table_name='poll_option')
    op.drop_table('poll_option')
    op.drop_table('Group_User')
    # ### end Alembic commands ###
