"""empty message

Revision ID: c63789b91571
Revises: c2d25b8d259d
Create Date: 2022-12-14 16:41:37.616761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c63789b91571'
down_revision = 'c2d25b8d259d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Poll_User_Vote',
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.alter_column('group', 'groupimage',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=True)
    op.add_column('poll_option', sa.Column('flightprice', sa.Float(), nullable=True))
    op.add_column('poll_option', sa.Column('departingairport', sa.String(length=3), nullable=True))
    op.add_column('poll_option', sa.Column('arrivinggairport', sa.String(length=3), nullable=True))
    op.add_column('poll_option', sa.Column('departingduration', sa.String(length=20), nullable=True))
    op.add_column('poll_option', sa.Column('arrivingduration', sa.String(length=20), nullable=True))
    op.drop_column('poll_option', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll_option', sa.Column('image', mysql.LONGTEXT(), nullable=True))
    op.drop_column('poll_option', 'arrivingduration')
    op.drop_column('poll_option', 'departingduration')
    op.drop_column('poll_option', 'arrivinggairport')
    op.drop_column('poll_option', 'departingairport')
    op.drop_column('poll_option', 'flightprice')
    op.alter_column('group', 'groupimage',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_table('group_user',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='group_user_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Poll_User_Vote')
    op.drop_table('Group_User')
    # ### end Alembic commands ###
