"""empty message

Revision ID: de8481a1b5ac
Revises: c1b708b89ca9
Create Date: 2022-11-29 12:28:23.465712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de8481a1b5ac'
down_revision = 'c1b708b89ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Group_User',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('group_user')
    op.alter_column('group', 'groupimage',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294000000),
               existing_nullable=True)
    op.drop_column('poll', 'option1')
    op.drop_column('poll', 'option2')
    op.drop_column('poll', 'option4')
    op.drop_column('poll', 'option5')
    op.drop_column('poll', 'option3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('option3', sa.BLOB(), nullable=True))
    op.add_column('poll', sa.Column('option5', sa.BLOB(), nullable=True))
    op.add_column('poll', sa.Column('option4', sa.BLOB(), nullable=True))
    op.add_column('poll', sa.Column('option2', sa.BLOB(), nullable=True))
    op.add_column('poll', sa.Column('option1', sa.BLOB(), nullable=True))
    op.alter_column('group', 'groupimage',
               existing_type=sa.Text(length=4294000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_table('group_user',
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='group_user_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Group_User')
    # ### end Alembic commands ###
